### PR TITLE
Move CI from CircleCI to Azure Pipelines

### PR DESCRIPTION
**Pull request by norio-nomura**

### CODE REVIEW

**Comment by norio-nomura** [comment]
Failing with `Permission denied` on `apt-get update && apt-get install -y …`: https://dev.azure.com/norio-nomura/OSS/_build/results?buildId=28&view=logs
Since most of docker images does not have `sudo`, this issue will block migrating CI using docker to Azure Pipelines.
/ref: [docker container root user - Developer Community](https://developercommunity.visualstudio.com/content/problem/336504/docker-container-root-user.html).
/cc: @DavidStaheli

**Comment by davidstaheli** [comment]
Investigating...

**Comment by chrispat** [comment]
@norio-nomura at the moment we have no way around that.  Certain pipeline operations like publishing artifacts and test results are taken care of by the agent which is running on the host under a particular UID and if the files are created as UID 0 inside the container then we are not able to read those files from the agent which is running on the VM host.  

The CircleCI images do have SUDO installed according to their docs https://circleci.com/docs/2.0/circleci-images/#pre-installed-tools.

**Comment by norio-nomura** [comment]
@chrisrpatterson: This package is Swift Library that depends on `libunwind8`.
I want to install [files](https://packages.ubuntu.com/xenial/amd64/libunwind8/filelist) in `libunwind8` package by `apt-get update && apt-get install -y libunwind8` to container that using `norionomura/swiftlint` images before testing.
I don't intended to writing files as root that need to be read from host.

> The CircleCI images do have SUDO installed according to their docs

I'm not using CircleCI images at all. But CircleCI allows `apt-get update && apt-get install -y libunwind8` on CI jobs with container using `norionomura/swiftlint` images.
e.g. https://circleci.com/gh/norio-nomura/SwiftBacktrace/147

**Comment by chrispat** [comment]
@norio-nomura thank you, we are looking at options on how to enable this sort of workflow while also not breaking the general expectations for users.  There is an active developer community post https://developercommunity.visualstudio.com/content/problem/336504/docker-container-root-user.html that has one suggestion for a potential solution we could provide.

**Comment by norio-nomura** [comment]
would retry when docker container root user comes to Azure Pipelines.

**Pull request closed without merging**
